CREATE TABLE [dbo].[UserPermissions] (
    [pk_PermissionID]          INT IDENTITY (1, 1) NOT NULL,
    [fk_UserID]                INT CONSTRAINT [DF_UserPermissions_fk_UserID] DEFAULT ((1)) NOT NULL,
    [AddProgramUsers]          BIT CONSTRAINT [DF_UserPermissions_AddProgramUsers] DEFAULT ((0)) NOT NULL,
    [AddPurchase]              BIT CONSTRAINT [DF_UserPermissions_CanAddPurchase] DEFAULT ((1)) NOT NULL,
    [AddSupply]                BIT CONSTRAINT [DF_UserPermissions_CanAddSupply] DEFAULT ((1)) NOT NULL,
    [AddDecoration]            BIT CONSTRAINT [DF_UserPermissions_CanAddDecoration] DEFAULT ((1)) NOT NULL,
    [AddFish]                  BIT CONSTRAINT [DF_UserPermissions_AddFish] DEFAULT ((1)) NOT NULL,
    [AddLivePlant]             BIT CONSTRAINT [DF_UserPermissions_AddLivePlant] DEFAULT ((1)) NOT NULL,
    [AddTank]                  BIT CONSTRAINT [DF_UserPermissions_AddTank] DEFAULT ((1)) NOT NULL,
    [EditProgramUsers]         BIT CONSTRAINT [DF_UserPermissions_EditProgramUsers] DEFAULT ((0)) NOT NULL,
    [EditPurchases]            BIT CONSTRAINT [DF_UserPermissions_CanEditPurchases] DEFAULT ((0)) NOT NULL,
    [EditSupply]               BIT CONSTRAINT [DF_UserPermissions_EditSupply] DEFAULT ((1)) NOT NULL,
    [EditDecorations]          BIT CONSTRAINT [DF_UserPermissions_EditDecorations] DEFAULT ((1)) NOT NULL,
    [EditFish]                 BIT CONSTRAINT [DF_UserPermissions_CanEditFish] DEFAULT ((0)) NOT NULL,
    [EditLivePlants]           BIT CONSTRAINT [DF_UserPermissions_EditLivePlants] DEFAULT ((1)) NOT NULL,
    [EditTanks]                BIT CONSTRAINT [DF_UserPermissions_CanEditTanks] DEFAULT ((0)) NOT NULL,
    [ViewGlobalPurchases]      BIT CONSTRAINT [DF_UserPermissions_CanAddTank] DEFAULT ((1)) NOT NULL,
    [DeleteProgramUsers]       BIT CONSTRAINT [DF_UserPermissions_DeleteProgramUsers] DEFAULT ((0)) NOT NULL,
    [DeletePurchases]          BIT CONSTRAINT [DF_UserPermissions_DeletePurchases] DEFAULT ((1)) NOT NULL,
    [DeleteSupply]             BIT CONSTRAINT [DF_UserPermissions_DeleteSupply] DEFAULT ((0)) NOT NULL,
    [DeleteDecoration]         BIT CONSTRAINT [DF_UserPermissions_DeleteDecoration] DEFAULT ((0)) NOT NULL,
    [DeleteFish]               BIT CONSTRAINT [DF_UserPermissions_DeleteFish] DEFAULT ((1)) NOT NULL,
    [DeletePlants]             BIT CONSTRAINT [DF_UserPermissions_DeletePlants] DEFAULT ((1)) NOT NULL,
    [DeleteTanks]              BIT CONSTRAINT [DF_UserPermissions_DeleteTanks] DEFAULT ((1)) NOT NULL,
    [RecordDeath]              BIT CONSTRAINT [DF_UserPermissions_RecordDeath] DEFAULT ((1)) NOT NULL,
    [RecordGlobalDeath]        BIT CONSTRAINT [DF_UserPermissions_RecordGlobalDeath] DEFAULT ((0)) NOT NULL,
    [PerformMaintenance]       BIT CONSTRAINT [DF_UserPermissions_PerformMaintenance] DEFAULT ((1)) NOT NULL,
    [PerformGlobalMaintenance] BIT CONSTRAINT [DF_UserPermissions_PerformGlobalMaintenance] DEFAULT ((0)) NOT NULL,
    [LoginWeb]                 BIT CONSTRAINT [DF_UserPermissions_CanLoginWeb] DEFAULT ((1)) NOT NULL,
    [LoginMobile]              BIT CONSTRAINT [DF_UserPermissions_CanLoginMobile] DEFAULT ((0)) NOT NULL,
    [LoginAPI]                 BIT CONSTRAINT [DF_UserPermissions_CanLoginAPI] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_UserPermissions] PRIMARY KEY CLUSTERED ([pk_PermissionID] ASC),
    CONSTRAINT [FK_UserPermissions_Users] FOREIGN KEY ([fk_UserID]) REFERENCES [dbo].[Users] ([pk_UserID])
);

