//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalTypes
    {
        public int pk_AnimalTypeID { get; set; }
        public Nullable<int> fk_FishCareGuideID { get; set; }
        public string AnimalTypeName { get; set; }
    
        public virtual FishCareGuides FishCareGuides { get; set; }
    }
}
