//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FishTypes> FishTypes { get; set; }
        public virtual DbSet<PurchaseLocations> PurchaseLocations { get; set; }
        public virtual DbSet<Purchases> Purchases { get; set; }
        public virtual DbSet<PurchaseTypes> PurchaseTypes { get; set; }
        public virtual DbSet<UserFish> UserFish { get; set; }
        public virtual DbSet<UserLoginSessions> UserLoginSessions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserTanks> UserTanks { get; set; }
        public virtual DbSet<GetFishTypes_vw> GetFishTypes_vw { get; set; }
    }
}
