//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Vendors
    {
        public int pk_VendorID { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> fk_ContactInfo { get; set; }
        public Nullable<int> fk_VendorType { get; set; }
    
        public virtual Business_List_VendorTypes Business_List_VendorTypes { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
    }
}
