//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Customers
    {
        public int pk_CustomerID { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public Nullable<int> fk_StoreID { get; set; }
        public Nullable<int> fk_UserProfileID { get; set; }
    
        public virtual Stores Stores { get; set; }
        public virtual UserProfiles UserProfiles { get; set; }
    }
}
