//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_List_TankTypes
    {
        public int pk_TankTypeID { get; set; }
        public string TypeName { get; set; }
        public int fk_WaterType { get; set; }
        public string TankSpecialTags { get; set; }
        public string TankShape { get; set; }
    
        public virtual List_WaterTypes List_WaterTypes { get; set; }
    }
}
