//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Business_Customers> Business_Customers { get; set; }
        public virtual DbSet<Business_List_VendorTypes> Business_List_VendorTypes { get; set; }
        public virtual DbSet<ContactInfo> ContactInfo { get; set; }
        public virtual DbSet<CrustaceanMoltRecords> CrustaceanMoltRecords { get; set; }
        public virtual DbSet<FishCareGuides> FishCareGuides { get; set; }
        public virtual DbSet<FishTypeDiseaseAffection> FishTypeDiseaseAffection { get; set; }
        public virtual DbSet<FishTypes> FishTypes { get; set; }
        public virtual DbSet<List_ActionTypes> List_ActionTypes { get; set; }
        public virtual DbSet<List_AnimalTypes> List_AnimalTypes { get; set; }
        public virtual DbSet<List_CollectionLocations> List_CollectionLocations { get; set; }
        public virtual DbSet<List_ContactTypes> List_ContactTypes { get; set; }
        public virtual DbSet<List_ErrorCategories> List_ErrorCategories { get; set; }
        public virtual DbSet<List_ErrorSeverityLevels> List_ErrorSeverityLevels { get; set; }
        public virtual DbSet<List_ErrorTypes> List_ErrorTypes { get; set; }
        public virtual DbSet<List_FishAgressionLevels> List_FishAgressionLevels { get; set; }
        public virtual DbSet<List_FishBirthingTypes> List_FishBirthingTypes { get; set; }
        public virtual DbSet<List_FishColors> List_FishColors { get; set; }
        public virtual DbSet<List_FishFamilyTypes> List_FishFamilyTypes { get; set; }
        public virtual DbSet<List_FishFeedingTypes> List_FishFeedingTypes { get; set; }
        public virtual DbSet<List_FishSexes> List_FishSexes { get; set; }
        public virtual DbSet<List_FishSicknessTypes> List_FishSicknessTypes { get; set; }
        public virtual DbSet<List_FishTerritorialLevels> List_FishTerritorialLevels { get; set; }
        public virtual DbSet<List_LivePlantDiseases> List_LivePlantDiseases { get; set; }
        public virtual DbSet<List_MedicalClassifications> List_MedicalClassifications { get; set; }
        public virtual DbSet<List_MedicalSubClassifications> List_MedicalSubClassifications { get; set; }
        public virtual DbSet<List_PlantSizeClasses> List_PlantSizeClasses { get; set; }
        public virtual DbSet<List_PurchaseCategories> List_PurchaseCategories { get; set; }
        public virtual DbSet<List_SupplyCategories> List_SupplyCategories { get; set; }
        public virtual DbSet<List_TankLightingLevels> List_TankLightingLevels { get; set; }
        public virtual DbSet<List_TankTestTypes> List_TankTestTypes { get; set; }
        public virtual DbSet<List_TankTypes> List_TankTypes { get; set; }
        public virtual DbSet<List_WaterTypes> List_WaterTypes { get; set; }
        public virtual DbSet<LivePlantTypes> LivePlantTypes { get; set; }
        public virtual DbSet<StoreHolidaySchedules> StoreHolidaySchedules { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
        public virtual DbSet<StoreWeeklySchedules> StoreWeeklySchedules { get; set; }
        public virtual DbSet<UserActionLogs> UserActionLogs { get; set; }
        public virtual DbSet<UserAuthenticationRoles> UserAuthenticationRoles { get; set; }
        public virtual DbSet<UserFish> UserFish { get; set; }
        public virtual DbSet<UserFishInventory> UserFishInventory { get; set; }
        public virtual DbSet<UserFishMedicalRecords> UserFishMedicalRecords { get; set; }
        public virtual DbSet<UserLivePlants> UserLivePlants { get; set; }
        public virtual DbSet<UserLoginSessions> UserLoginSessions { get; set; }
        public virtual DbSet<UserNotifications> UserNotifications { get; set; }
        public virtual DbSet<UserPermissions> UserPermissions { get; set; }
        public virtual DbSet<UserProfiles> UserProfiles { get; set; }
        public virtual DbSet<UserPurchases> UserPurchases { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserTanks> UserTanks { get; set; }
        public virtual DbSet<UserTankSupplyInventory> UserTankSupplyInventory { get; set; }
        public virtual DbSet<UserTankTemperatureLogs> UserTankTemperatureLogs { get; set; }
        public virtual DbSet<UserTankTests> UserTankTests { get; set; }
        public virtual DbSet<Business_Vendors> Business_Vendors { get; set; }
        public virtual DbSet<Errorlogs> Errorlogs { get; set; }
        public virtual DbSet<vw_FishDictionary> vw_FishDictionary { get; set; }
        public virtual DbSet<vw_MasterFishDictionary> vw_MasterFishDictionary { get; set; }
        public virtual DbSet<vw_MasterFishView> vw_MasterFishView { get; set; }
        public virtual DbSet<vw_PlantDictionary> vw_PlantDictionary { get; set; }
        public virtual DbSet<vw_UserOverview> vw_UserOverview { get; set; }
        public virtual DbSet<vw_UserPurchases> vw_UserPurchases { get; set; }
        public virtual DbSet<vw_UserSessions> vw_UserSessions { get; set; }
        public virtual DbSet<vw_UserSupplies> vw_UserSupplies { get; set; }
        public virtual DbSet<vw_UserTanks> vw_UserTanks { get; set; }
    
        public virtual int Add_PlantType(string plantName, Nullable<int> lightingLevel, Nullable<bool> needsFertilizer, Nullable<bool> canFloat, Nullable<int> minTemperature, Nullable<int> maxTemperature, Nullable<int> idealTemperature, Nullable<double> maxHeight, Nullable<int> plantSizeClass, Nullable<int> purchaseCategory, string plantImage)
        {
            var plantNameParameter = plantName != null ?
                new ObjectParameter("PlantName", plantName) :
                new ObjectParameter("PlantName", typeof(string));
    
            var lightingLevelParameter = lightingLevel.HasValue ?
                new ObjectParameter("LightingLevel", lightingLevel) :
                new ObjectParameter("LightingLevel", typeof(int));
    
            var needsFertilizerParameter = needsFertilizer.HasValue ?
                new ObjectParameter("NeedsFertilizer", needsFertilizer) :
                new ObjectParameter("NeedsFertilizer", typeof(bool));
    
            var canFloatParameter = canFloat.HasValue ?
                new ObjectParameter("CanFloat", canFloat) :
                new ObjectParameter("CanFloat", typeof(bool));
    
            var minTemperatureParameter = minTemperature.HasValue ?
                new ObjectParameter("MinTemperature", minTemperature) :
                new ObjectParameter("MinTemperature", typeof(int));
    
            var maxTemperatureParameter = maxTemperature.HasValue ?
                new ObjectParameter("MaxTemperature", maxTemperature) :
                new ObjectParameter("MaxTemperature", typeof(int));
    
            var idealTemperatureParameter = idealTemperature.HasValue ?
                new ObjectParameter("IdealTemperature", idealTemperature) :
                new ObjectParameter("IdealTemperature", typeof(int));
    
            var maxHeightParameter = maxHeight.HasValue ?
                new ObjectParameter("MaxHeight", maxHeight) :
                new ObjectParameter("MaxHeight", typeof(double));
    
            var plantSizeClassParameter = plantSizeClass.HasValue ?
                new ObjectParameter("PlantSizeClass", plantSizeClass) :
                new ObjectParameter("PlantSizeClass", typeof(int));
    
            var purchaseCategoryParameter = purchaseCategory.HasValue ?
                new ObjectParameter("PurchaseCategory", purchaseCategory) :
                new ObjectParameter("PurchaseCategory", typeof(int));
    
            var plantImageParameter = plantImage != null ?
                new ObjectParameter("PlantImage", plantImage) :
                new ObjectParameter("PlantImage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_PlantType", plantNameParameter, lightingLevelParameter, needsFertilizerParameter, canFloatParameter, minTemperatureParameter, maxTemperatureParameter, idealTemperatureParameter, maxHeightParameter, plantSizeClassParameter, purchaseCategoryParameter, plantImageParameter);
        }
    
        public virtual int Add_User(string userName, string password, string emailAddress, string userRole)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("UserRole", userRole) :
                new ObjectParameter("UserRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_User", userNameParameter, passwordParameter, emailAddressParameter, userRoleParameter);
        }
    
        public virtual int Add_UserPlant(Nullable<int> userID, Nullable<int> tankID, Nullable<int> purchaseID, Nullable<int> plantType)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var tankIDParameter = tankID.HasValue ?
                new ObjectParameter("TankID", tankID) :
                new ObjectParameter("TankID", typeof(int));
    
            var purchaseIDParameter = purchaseID.HasValue ?
                new ObjectParameter("PurchaseID", purchaseID) :
                new ObjectParameter("PurchaseID", typeof(int));
    
            var plantTypeParameter = plantType.HasValue ?
                new ObjectParameter("PlantType", plantType) :
                new ObjectParameter("PlantType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_UserPlant", userIDParameter, tankIDParameter, purchaseIDParameter, plantTypeParameter);
        }
    
        public virtual int Add_UserPurchase(Nullable<int> quantity, Nullable<decimal> cost, Nullable<System.DateTime> date, Nullable<int> storeID, Nullable<int> purchaseCategory, Nullable<int> userID, string description, Nullable<int> userTank, Nullable<int> fishType, Nullable<int> livePlantType)
        {
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            var costParameter = cost.HasValue ?
                new ObjectParameter("Cost", cost) :
                new ObjectParameter("Cost", typeof(decimal));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var storeIDParameter = storeID.HasValue ?
                new ObjectParameter("StoreID", storeID) :
                new ObjectParameter("StoreID", typeof(int));
    
            var purchaseCategoryParameter = purchaseCategory.HasValue ?
                new ObjectParameter("PurchaseCategory", purchaseCategory) :
                new ObjectParameter("PurchaseCategory", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var userTankParameter = userTank.HasValue ?
                new ObjectParameter("UserTank", userTank) :
                new ObjectParameter("UserTank", typeof(int));
    
            var fishTypeParameter = fishType.HasValue ?
                new ObjectParameter("FishType", fishType) :
                new ObjectParameter("FishType", typeof(int));
    
            var livePlantTypeParameter = livePlantType.HasValue ?
                new ObjectParameter("LivePlantType", livePlantType) :
                new ObjectParameter("LivePlantType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_UserPurchase", quantityParameter, costParameter, dateParameter, storeIDParameter, purchaseCategoryParameter, userIDParameter, descriptionParameter, userTankParameter, fishTypeParameter, livePlantTypeParameter);
        }
    
        public virtual int Add_UserTank(Nullable<int> tankOwnerID, Nullable<int> tankSize, Nullable<decimal> tankHeight, Nullable<decimal> tankWidth, Nullable<int> waterType, Nullable<int> tankType)
        {
            var tankOwnerIDParameter = tankOwnerID.HasValue ?
                new ObjectParameter("TankOwnerID", tankOwnerID) :
                new ObjectParameter("TankOwnerID", typeof(int));
    
            var tankSizeParameter = tankSize.HasValue ?
                new ObjectParameter("TankSize", tankSize) :
                new ObjectParameter("TankSize", typeof(int));
    
            var tankHeightParameter = tankHeight.HasValue ?
                new ObjectParameter("TankHeight", tankHeight) :
                new ObjectParameter("TankHeight", typeof(decimal));
    
            var tankWidthParameter = tankWidth.HasValue ?
                new ObjectParameter("TankWidth", tankWidth) :
                new ObjectParameter("TankWidth", typeof(decimal));
    
            var waterTypeParameter = waterType.HasValue ?
                new ObjectParameter("WaterType", waterType) :
                new ObjectParameter("WaterType", typeof(int));
    
            var tankTypeParameter = tankType.HasValue ?
                new ObjectParameter("TankType", tankType) :
                new ObjectParameter("TankType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_UserTank", tankOwnerIDParameter, tankSizeParameter, tankHeightParameter, tankWidthParameter, waterTypeParameter, tankTypeParameter);
        }
    
        public virtual int ContactInfo_Add(string firstName, string lastName, string streetAddress, string city, string state, string zip, string phone, string altEmail, string website, Nullable<int> contactType)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var streetAddressParameter = streetAddress != null ?
                new ObjectParameter("StreetAddress", streetAddress) :
                new ObjectParameter("StreetAddress", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("Zip", zip) :
                new ObjectParameter("Zip", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var altEmailParameter = altEmail != null ?
                new ObjectParameter("AltEmail", altEmail) :
                new ObjectParameter("AltEmail", typeof(string));
    
            var websiteParameter = website != null ?
                new ObjectParameter("Website", website) :
                new ObjectParameter("Website", typeof(string));
    
            var contactTypeParameter = contactType.HasValue ?
                new ObjectParameter("ContactType", contactType) :
                new ObjectParameter("ContactType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ContactInfo_Add", firstNameParameter, lastNameParameter, streetAddressParameter, cityParameter, stateParameter, zipParameter, phoneParameter, altEmailParameter, websiteParameter, contactTypeParameter);
        }
    
        public virtual ObjectResult<Get_TankFish_Result> Get_TankFish(Nullable<int> tankID)
        {
            var tankIDParameter = tankID.HasValue ?
                new ObjectParameter("TankID", tankID) :
                new ObjectParameter("TankID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_TankFish_Result>("Get_TankFish", tankIDParameter);
        }
    
        public virtual ObjectResult<GetUserPurchases_Result> GetUserPurchases(Nullable<int> userID, Nullable<int> purchaseCategory)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var purchaseCategoryParameter = purchaseCategory.HasValue ?
                new ObjectParameter("PurchaseCategory", purchaseCategory) :
                new ObjectParameter("PurchaseCategory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserPurchases_Result>("GetUserPurchases", userIDParameter, purchaseCategoryParameter);
        }
    
        public virtual int RecordFishDeath(Nullable<int> fishID, Nullable<System.DateTime> timeOfDeath, string description, Nullable<int> classification, Nullable<int> subClassification)
        {
            var fishIDParameter = fishID.HasValue ?
                new ObjectParameter("FishID", fishID) :
                new ObjectParameter("FishID", typeof(int));
    
            var timeOfDeathParameter = timeOfDeath.HasValue ?
                new ObjectParameter("TimeOfDeath", timeOfDeath) :
                new ObjectParameter("TimeOfDeath", typeof(System.DateTime));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var classificationParameter = classification.HasValue ?
                new ObjectParameter("Classification", classification) :
                new ObjectParameter("Classification", typeof(int));
    
            var subClassificationParameter = subClassification.HasValue ?
                new ObjectParameter("SubClassification", subClassification) :
                new ObjectParameter("SubClassification", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RecordFishDeath", fishIDParameter, timeOfDeathParameter, descriptionParameter, classificationParameter, subClassificationParameter);
        }
    
        public virtual int UserLoginSession_Add(Nullable<int> sessionID, Nullable<int> userID, Nullable<System.DateTime> sessionBegin, Nullable<System.DateTime> sessionEnd, string sessionPermission, Nullable<int> isSessionActive)
        {
            var sessionIDParameter = sessionID.HasValue ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var sessionBeginParameter = sessionBegin.HasValue ?
                new ObjectParameter("SessionBegin", sessionBegin) :
                new ObjectParameter("SessionBegin", typeof(System.DateTime));
    
            var sessionEndParameter = sessionEnd.HasValue ?
                new ObjectParameter("SessionEnd", sessionEnd) :
                new ObjectParameter("SessionEnd", typeof(System.DateTime));
    
            var sessionPermissionParameter = sessionPermission != null ?
                new ObjectParameter("SessionPermission", sessionPermission) :
                new ObjectParameter("SessionPermission", typeof(string));
    
            var isSessionActiveParameter = isSessionActive.HasValue ?
                new ObjectParameter("IsSessionActive", isSessionActive) :
                new ObjectParameter("IsSessionActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserLoginSession_Add", sessionIDParameter, userIDParameter, sessionBeginParameter, sessionEndParameter, sessionPermissionParameter, isSessionActiveParameter);
        }
    
        public virtual int UserPermissionsRecord_Add(Nullable<bool> addProgramUsers, Nullable<bool> addPurchase, Nullable<bool> addSupply, Nullable<bool> addDecoration, Nullable<bool> addFish, Nullable<bool> addLivePlant, Nullable<bool> addTank, Nullable<bool> editProgramUsers, Nullable<bool> editPurchases, Nullable<bool> editSupply, Nullable<bool> editDecorations, Nullable<bool> editFish, Nullable<bool> editLivePlants, Nullable<bool> editTanks, Nullable<bool> viewGlobalPurchases, Nullable<bool> deleteProgramUsers, Nullable<bool> deletePurchases, Nullable<bool> deleteSupply, Nullable<bool> deleteDecoration, Nullable<bool> deleteFish, Nullable<bool> deletePlants, Nullable<bool> deleteTanks, Nullable<bool> recordDeath, Nullable<bool> recordGlobalDeath, Nullable<bool> performMaintenance, Nullable<bool> performGlobalMaintenance, Nullable<bool> loginWeb, Nullable<bool> loginMobile, Nullable<bool> loginAPI)
        {
            var addProgramUsersParameter = addProgramUsers.HasValue ?
                new ObjectParameter("AddProgramUsers", addProgramUsers) :
                new ObjectParameter("AddProgramUsers", typeof(bool));
    
            var addPurchaseParameter = addPurchase.HasValue ?
                new ObjectParameter("AddPurchase", addPurchase) :
                new ObjectParameter("AddPurchase", typeof(bool));
    
            var addSupplyParameter = addSupply.HasValue ?
                new ObjectParameter("AddSupply", addSupply) :
                new ObjectParameter("AddSupply", typeof(bool));
    
            var addDecorationParameter = addDecoration.HasValue ?
                new ObjectParameter("AddDecoration", addDecoration) :
                new ObjectParameter("AddDecoration", typeof(bool));
    
            var addFishParameter = addFish.HasValue ?
                new ObjectParameter("AddFish", addFish) :
                new ObjectParameter("AddFish", typeof(bool));
    
            var addLivePlantParameter = addLivePlant.HasValue ?
                new ObjectParameter("AddLivePlant", addLivePlant) :
                new ObjectParameter("AddLivePlant", typeof(bool));
    
            var addTankParameter = addTank.HasValue ?
                new ObjectParameter("AddTank", addTank) :
                new ObjectParameter("AddTank", typeof(bool));
    
            var editProgramUsersParameter = editProgramUsers.HasValue ?
                new ObjectParameter("EditProgramUsers", editProgramUsers) :
                new ObjectParameter("EditProgramUsers", typeof(bool));
    
            var editPurchasesParameter = editPurchases.HasValue ?
                new ObjectParameter("EditPurchases", editPurchases) :
                new ObjectParameter("EditPurchases", typeof(bool));
    
            var editSupplyParameter = editSupply.HasValue ?
                new ObjectParameter("EditSupply", editSupply) :
                new ObjectParameter("EditSupply", typeof(bool));
    
            var editDecorationsParameter = editDecorations.HasValue ?
                new ObjectParameter("EditDecorations", editDecorations) :
                new ObjectParameter("EditDecorations", typeof(bool));
    
            var editFishParameter = editFish.HasValue ?
                new ObjectParameter("EditFish", editFish) :
                new ObjectParameter("EditFish", typeof(bool));
    
            var editLivePlantsParameter = editLivePlants.HasValue ?
                new ObjectParameter("EditLivePlants", editLivePlants) :
                new ObjectParameter("EditLivePlants", typeof(bool));
    
            var editTanksParameter = editTanks.HasValue ?
                new ObjectParameter("EditTanks", editTanks) :
                new ObjectParameter("EditTanks", typeof(bool));
    
            var viewGlobalPurchasesParameter = viewGlobalPurchases.HasValue ?
                new ObjectParameter("ViewGlobalPurchases", viewGlobalPurchases) :
                new ObjectParameter("ViewGlobalPurchases", typeof(bool));
    
            var deleteProgramUsersParameter = deleteProgramUsers.HasValue ?
                new ObjectParameter("DeleteProgramUsers", deleteProgramUsers) :
                new ObjectParameter("DeleteProgramUsers", typeof(bool));
    
            var deletePurchasesParameter = deletePurchases.HasValue ?
                new ObjectParameter("DeletePurchases", deletePurchases) :
                new ObjectParameter("DeletePurchases", typeof(bool));
    
            var deleteSupplyParameter = deleteSupply.HasValue ?
                new ObjectParameter("DeleteSupply", deleteSupply) :
                new ObjectParameter("DeleteSupply", typeof(bool));
    
            var deleteDecorationParameter = deleteDecoration.HasValue ?
                new ObjectParameter("DeleteDecoration", deleteDecoration) :
                new ObjectParameter("DeleteDecoration", typeof(bool));
    
            var deleteFishParameter = deleteFish.HasValue ?
                new ObjectParameter("DeleteFish", deleteFish) :
                new ObjectParameter("DeleteFish", typeof(bool));
    
            var deletePlantsParameter = deletePlants.HasValue ?
                new ObjectParameter("DeletePlants", deletePlants) :
                new ObjectParameter("DeletePlants", typeof(bool));
    
            var deleteTanksParameter = deleteTanks.HasValue ?
                new ObjectParameter("DeleteTanks", deleteTanks) :
                new ObjectParameter("DeleteTanks", typeof(bool));
    
            var recordDeathParameter = recordDeath.HasValue ?
                new ObjectParameter("RecordDeath", recordDeath) :
                new ObjectParameter("RecordDeath", typeof(bool));
    
            var recordGlobalDeathParameter = recordGlobalDeath.HasValue ?
                new ObjectParameter("RecordGlobalDeath", recordGlobalDeath) :
                new ObjectParameter("RecordGlobalDeath", typeof(bool));
    
            var performMaintenanceParameter = performMaintenance.HasValue ?
                new ObjectParameter("PerformMaintenance", performMaintenance) :
                new ObjectParameter("PerformMaintenance", typeof(bool));
    
            var performGlobalMaintenanceParameter = performGlobalMaintenance.HasValue ?
                new ObjectParameter("PerformGlobalMaintenance", performGlobalMaintenance) :
                new ObjectParameter("PerformGlobalMaintenance", typeof(bool));
    
            var loginWebParameter = loginWeb.HasValue ?
                new ObjectParameter("LoginWeb", loginWeb) :
                new ObjectParameter("LoginWeb", typeof(bool));
    
            var loginMobileParameter = loginMobile.HasValue ?
                new ObjectParameter("LoginMobile", loginMobile) :
                new ObjectParameter("LoginMobile", typeof(bool));
    
            var loginAPIParameter = loginAPI.HasValue ?
                new ObjectParameter("LoginAPI", loginAPI) :
                new ObjectParameter("LoginAPI", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserPermissionsRecord_Add", addProgramUsersParameter, addPurchaseParameter, addSupplyParameter, addDecorationParameter, addFishParameter, addLivePlantParameter, addTankParameter, editProgramUsersParameter, editPurchasesParameter, editSupplyParameter, editDecorationsParameter, editFishParameter, editLivePlantsParameter, editTanksParameter, viewGlobalPurchasesParameter, deleteProgramUsersParameter, deletePurchasesParameter, deleteSupplyParameter, deleteDecorationParameter, deleteFishParameter, deletePlantsParameter, deleteTanksParameter, recordDeathParameter, recordGlobalDeathParameter, performMaintenanceParameter, performGlobalMaintenanceParameter, loginWebParameter, loginMobileParameter, loginAPIParameter);
        }
    
        public virtual int UserProfiles_Add(Nullable<int> fk_ContactInfo, Nullable<int> fk_Permissions)
        {
            var fk_ContactInfoParameter = fk_ContactInfo.HasValue ?
                new ObjectParameter("fk_ContactInfo", fk_ContactInfo) :
                new ObjectParameter("fk_ContactInfo", typeof(int));
    
            var fk_PermissionsParameter = fk_Permissions.HasValue ?
                new ObjectParameter("fk_Permissions", fk_Permissions) :
                new ObjectParameter("fk_Permissions", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserProfiles_Add", fk_ContactInfoParameter, fk_PermissionsParameter);
        }
    
        public virtual int Users_Add(Nullable<int> fk_ProfileID, string emailAddress, string userName, string password)
        {
            var fk_ProfileIDParameter = fk_ProfileID.HasValue ?
                new ObjectParameter("fk_ProfileID", fk_ProfileID) :
                new ObjectParameter("fk_ProfileID", typeof(int));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Users_Add", fk_ProfileIDParameter, emailAddressParameter, userNameParameter, passwordParameter);
        }
    
        public virtual int UserLoginSession_Add1(string sessionID, Nullable<int> userID, Nullable<System.DateTime> sessionBegin, Nullable<System.DateTime> sessionEnd, string sessionPermission, Nullable<int> isSessionActive)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var sessionBeginParameter = sessionBegin.HasValue ?
                new ObjectParameter("SessionBegin", sessionBegin) :
                new ObjectParameter("SessionBegin", typeof(System.DateTime));
    
            var sessionEndParameter = sessionEnd.HasValue ?
                new ObjectParameter("SessionEnd", sessionEnd) :
                new ObjectParameter("SessionEnd", typeof(System.DateTime));
    
            var sessionPermissionParameter = sessionPermission != null ?
                new ObjectParameter("SessionPermission", sessionPermission) :
                new ObjectParameter("SessionPermission", typeof(string));
    
            var isSessionActiveParameter = isSessionActive.HasValue ?
                new ObjectParameter("IsSessionActive", isSessionActive) :
                new ObjectParameter("IsSessionActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserLoginSession_Add1", sessionIDParameter, userIDParameter, sessionBeginParameter, sessionEndParameter, sessionPermissionParameter, isSessionActiveParameter);
        }
    
        public virtual int UserLoginSessions_Add(string sessionID, Nullable<int> userID, Nullable<System.DateTime> sessionBegin, Nullable<System.DateTime> sessionEnd, string sessionPermission, Nullable<int> isSessionActive)
        {
            var sessionIDParameter = sessionID != null ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var sessionBeginParameter = sessionBegin.HasValue ?
                new ObjectParameter("SessionBegin", sessionBegin) :
                new ObjectParameter("SessionBegin", typeof(System.DateTime));
    
            var sessionEndParameter = sessionEnd.HasValue ?
                new ObjectParameter("SessionEnd", sessionEnd) :
                new ObjectParameter("SessionEnd", typeof(System.DateTime));
    
            var sessionPermissionParameter = sessionPermission != null ?
                new ObjectParameter("SessionPermission", sessionPermission) :
                new ObjectParameter("SessionPermission", typeof(string));
    
            var isSessionActiveParameter = isSessionActive.HasValue ?
                new ObjectParameter("IsSessionActive", isSessionActive) :
                new ObjectParameter("IsSessionActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserLoginSessions_Add", sessionIDParameter, userIDParameter, sessionBeginParameter, sessionEndParameter, sessionPermissionParameter, isSessionActiveParameter);
        }
    }
}
