//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Business_Customers> Business_Customers { get; set; }
        public virtual DbSet<Business_List_VendorTypes> Business_List_VendorTypes { get; set; }
        public virtual DbSet<ContactInfo> ContactInfo { get; set; }
        public virtual DbSet<CrustaceanMoltRecords> CrustaceanMoltRecords { get; set; }
        public virtual DbSet<FishCareGuides> FishCareGuides { get; set; }
        public virtual DbSet<FishTypeDiseaseAffection> FishTypeDiseaseAffection { get; set; }
        public virtual DbSet<FishTypes> FishTypes { get; set; }
        public virtual DbSet<List_ActionTypes> List_ActionTypes { get; set; }
        public virtual DbSet<List_AnimalTypes> List_AnimalTypes { get; set; }
        public virtual DbSet<List_CollectionLocations> List_CollectionLocations { get; set; }
        public virtual DbSet<List_ContactTypes> List_ContactTypes { get; set; }
        public virtual DbSet<List_ErrorCategories> List_ErrorCategories { get; set; }
        public virtual DbSet<List_ErrorSeverityLevels> List_ErrorSeverityLevels { get; set; }
        public virtual DbSet<List_ErrorTypes> List_ErrorTypes { get; set; }
        public virtual DbSet<List_FishAgressionLevels> List_FishAgressionLevels { get; set; }
        public virtual DbSet<List_FishBirthingTypes> List_FishBirthingTypes { get; set; }
        public virtual DbSet<List_FishColors> List_FishColors { get; set; }
        public virtual DbSet<List_FishFamilyTypes> List_FishFamilyTypes { get; set; }
        public virtual DbSet<List_FishFeedingTypes> List_FishFeedingTypes { get; set; }
        public virtual DbSet<List_FishSexes> List_FishSexes { get; set; }
        public virtual DbSet<List_FishSicknessTypes> List_FishSicknessTypes { get; set; }
        public virtual DbSet<List_FishTerritorialLevels> List_FishTerritorialLevels { get; set; }
        public virtual DbSet<List_LivePlantDiseases> List_LivePlantDiseases { get; set; }
        public virtual DbSet<List_MedicalClassifications> List_MedicalClassifications { get; set; }
        public virtual DbSet<List_MedicalSubClassifications> List_MedicalSubClassifications { get; set; }
        public virtual DbSet<List_PlantSizeClasses> List_PlantSizeClasses { get; set; }
        public virtual DbSet<List_PurchaseCategories> List_PurchaseCategories { get; set; }
        public virtual DbSet<List_SupplyCategories> List_SupplyCategories { get; set; }
        public virtual DbSet<List_TankLightingLevels> List_TankLightingLevels { get; set; }
        public virtual DbSet<List_TankTestTypes> List_TankTestTypes { get; set; }
        public virtual DbSet<List_TankTypes> List_TankTypes { get; set; }
        public virtual DbSet<List_WaterTypes> List_WaterTypes { get; set; }
        public virtual DbSet<LivePlantTypes> LivePlantTypes { get; set; }
        public virtual DbSet<StoreHolidaySchedules> StoreHolidaySchedules { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
        public virtual DbSet<StoreWeeklySchedules> StoreWeeklySchedules { get; set; }
        public virtual DbSet<UserActionLogs> UserActionLogs { get; set; }
        public virtual DbSet<UserAuthenticationRoles> UserAuthenticationRoles { get; set; }
        public virtual DbSet<UserFish> UserFish { get; set; }
        public virtual DbSet<UserFishInventory> UserFishInventory { get; set; }
        public virtual DbSet<UserFishMedicalRecords> UserFishMedicalRecords { get; set; }
        public virtual DbSet<UserLivePlants> UserLivePlants { get; set; }
        public virtual DbSet<UserLoginSessions> UserLoginSessions { get; set; }
        public virtual DbSet<UserNotifications> UserNotifications { get; set; }
        public virtual DbSet<UserPermissions> UserPermissions { get; set; }
        public virtual DbSet<UserProfiles> UserProfiles { get; set; }
        public virtual DbSet<UserPurchases> UserPurchases { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserTanks> UserTanks { get; set; }
        public virtual DbSet<UserTankSupplyInventory> UserTankSupplyInventory { get; set; }
        public virtual DbSet<UserTankTemperatureLogs> UserTankTemperatureLogs { get; set; }
        public virtual DbSet<UserTankTests> UserTankTests { get; set; }
        public virtual DbSet<Business_Vendors> Business_Vendors { get; set; }
        public virtual DbSet<Errorlogs> Errorlogs { get; set; }
        public virtual DbSet<vw_FishDictionary> vw_FishDictionary { get; set; }
        public virtual DbSet<vw_MasterFishDictionary> vw_MasterFishDictionary { get; set; }
        public virtual DbSet<vw_MasterFishView> vw_MasterFishView { get; set; }
        public virtual DbSet<vw_PlantDictionary> vw_PlantDictionary { get; set; }
        public virtual DbSet<vw_UserOverview> vw_UserOverview { get; set; }
        public virtual DbSet<vw_UserPurchases> vw_UserPurchases { get; set; }
        public virtual DbSet<vw_UserSessions> vw_UserSessions { get; set; }
        public virtual DbSet<vw_UserSupplies> vw_UserSupplies { get; set; }
        public virtual DbSet<vw_UserTanks> vw_UserTanks { get; set; }
    
        public virtual int Add_PlantType(string plantName, Nullable<int> lightingLevel, Nullable<bool> needsFertilizer, Nullable<bool> canFloat, Nullable<int> minTemperature, Nullable<int> maxTemperature, Nullable<int> idealTemperature, Nullable<double> maxHeight, Nullable<int> plantSizeClass, Nullable<int> purchaseCategory, string plantImage)
        {
            var plantNameParameter = plantName != null ?
                new ObjectParameter("PlantName", plantName) :
                new ObjectParameter("PlantName", typeof(string));
    
            var lightingLevelParameter = lightingLevel.HasValue ?
                new ObjectParameter("LightingLevel", lightingLevel) :
                new ObjectParameter("LightingLevel", typeof(int));
    
            var needsFertilizerParameter = needsFertilizer.HasValue ?
                new ObjectParameter("NeedsFertilizer", needsFertilizer) :
                new ObjectParameter("NeedsFertilizer", typeof(bool));
    
            var canFloatParameter = canFloat.HasValue ?
                new ObjectParameter("CanFloat", canFloat) :
                new ObjectParameter("CanFloat", typeof(bool));
    
            var minTemperatureParameter = minTemperature.HasValue ?
                new ObjectParameter("MinTemperature", minTemperature) :
                new ObjectParameter("MinTemperature", typeof(int));
    
            var maxTemperatureParameter = maxTemperature.HasValue ?
                new ObjectParameter("MaxTemperature", maxTemperature) :
                new ObjectParameter("MaxTemperature", typeof(int));
    
            var idealTemperatureParameter = idealTemperature.HasValue ?
                new ObjectParameter("IdealTemperature", idealTemperature) :
                new ObjectParameter("IdealTemperature", typeof(int));
    
            var maxHeightParameter = maxHeight.HasValue ?
                new ObjectParameter("MaxHeight", maxHeight) :
                new ObjectParameter("MaxHeight", typeof(double));
    
            var plantSizeClassParameter = plantSizeClass.HasValue ?
                new ObjectParameter("PlantSizeClass", plantSizeClass) :
                new ObjectParameter("PlantSizeClass", typeof(int));
    
            var purchaseCategoryParameter = purchaseCategory.HasValue ?
                new ObjectParameter("PurchaseCategory", purchaseCategory) :
                new ObjectParameter("PurchaseCategory", typeof(int));
    
            var plantImageParameter = plantImage != null ?
                new ObjectParameter("PlantImage", plantImage) :
                new ObjectParameter("PlantImage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_PlantType", plantNameParameter, lightingLevelParameter, needsFertilizerParameter, canFloatParameter, minTemperatureParameter, maxTemperatureParameter, idealTemperatureParameter, maxHeightParameter, plantSizeClassParameter, purchaseCategoryParameter, plantImageParameter);
        }
    
        public virtual int Add_User(string userName, string password, string emailAddress, string userRole)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var userRoleParameter = userRole != null ?
                new ObjectParameter("UserRole", userRole) :
                new ObjectParameter("UserRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_User", userNameParameter, passwordParameter, emailAddressParameter, userRoleParameter);
        }
    
        public virtual int Add_UserPlant(Nullable<int> userID, Nullable<int> tankID, Nullable<int> purchaseID, Nullable<int> plantType)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var tankIDParameter = tankID.HasValue ?
                new ObjectParameter("TankID", tankID) :
                new ObjectParameter("TankID", typeof(int));
    
            var purchaseIDParameter = purchaseID.HasValue ?
                new ObjectParameter("PurchaseID", purchaseID) :
                new ObjectParameter("PurchaseID", typeof(int));
    
            var plantTypeParameter = plantType.HasValue ?
                new ObjectParameter("PlantType", plantType) :
                new ObjectParameter("PlantType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_UserPlant", userIDParameter, tankIDParameter, purchaseIDParameter, plantTypeParameter);
        }
    
        public virtual int Add_UserPurchase(Nullable<int> quantity, Nullable<decimal> cost, Nullable<System.DateTime> date, Nullable<int> storeID, Nullable<int> purchaseCategory, Nullable<int> userID, string description, Nullable<int> userTank, Nullable<int> fishType, Nullable<int> livePlantType)
        {
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            var costParameter = cost.HasValue ?
                new ObjectParameter("Cost", cost) :
                new ObjectParameter("Cost", typeof(decimal));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var storeIDParameter = storeID.HasValue ?
                new ObjectParameter("StoreID", storeID) :
                new ObjectParameter("StoreID", typeof(int));
    
            var purchaseCategoryParameter = purchaseCategory.HasValue ?
                new ObjectParameter("PurchaseCategory", purchaseCategory) :
                new ObjectParameter("PurchaseCategory", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var userTankParameter = userTank.HasValue ?
                new ObjectParameter("UserTank", userTank) :
                new ObjectParameter("UserTank", typeof(int));
    
            var fishTypeParameter = fishType.HasValue ?
                new ObjectParameter("FishType", fishType) :
                new ObjectParameter("FishType", typeof(int));
    
            var livePlantTypeParameter = livePlantType.HasValue ?
                new ObjectParameter("LivePlantType", livePlantType) :
                new ObjectParameter("LivePlantType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_UserPurchase", quantityParameter, costParameter, dateParameter, storeIDParameter, purchaseCategoryParameter, userIDParameter, descriptionParameter, userTankParameter, fishTypeParameter, livePlantTypeParameter);
        }
    
        public virtual int Add_UserTank(Nullable<int> tankOwnerID, Nullable<int> tankSize, Nullable<decimal> tankHeight, Nullable<decimal> tankWidth, Nullable<int> waterType, Nullable<int> tankType)
        {
            var tankOwnerIDParameter = tankOwnerID.HasValue ?
                new ObjectParameter("TankOwnerID", tankOwnerID) :
                new ObjectParameter("TankOwnerID", typeof(int));
    
            var tankSizeParameter = tankSize.HasValue ?
                new ObjectParameter("TankSize", tankSize) :
                new ObjectParameter("TankSize", typeof(int));
    
            var tankHeightParameter = tankHeight.HasValue ?
                new ObjectParameter("TankHeight", tankHeight) :
                new ObjectParameter("TankHeight", typeof(decimal));
    
            var tankWidthParameter = tankWidth.HasValue ?
                new ObjectParameter("TankWidth", tankWidth) :
                new ObjectParameter("TankWidth", typeof(decimal));
    
            var waterTypeParameter = waterType.HasValue ?
                new ObjectParameter("WaterType", waterType) :
                new ObjectParameter("WaterType", typeof(int));
    
            var tankTypeParameter = tankType.HasValue ?
                new ObjectParameter("TankType", tankType) :
                new ObjectParameter("TankType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_UserTank", tankOwnerIDParameter, tankSizeParameter, tankHeightParameter, tankWidthParameter, waterTypeParameter, tankTypeParameter);
        }
    
        public virtual ObjectResult<Get_TankFish_Result> Get_TankFish(Nullable<int> tankID)
        {
            var tankIDParameter = tankID.HasValue ?
                new ObjectParameter("TankID", tankID) :
                new ObjectParameter("TankID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_TankFish_Result>("Get_TankFish", tankIDParameter);
        }
    
        public virtual ObjectResult<GetUserPurchases_Result> GetUserPurchases(Nullable<int> userID, Nullable<int> purchaseCategory)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var purchaseCategoryParameter = purchaseCategory.HasValue ?
                new ObjectParameter("PurchaseCategory", purchaseCategory) :
                new ObjectParameter("PurchaseCategory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserPurchases_Result>("GetUserPurchases", userIDParameter, purchaseCategoryParameter);
        }
    
        public virtual int RecordFishDeath(Nullable<int> fishID, Nullable<System.DateTime> timeOfDeath, string description, Nullable<int> classification, Nullable<int> subClassification)
        {
            var fishIDParameter = fishID.HasValue ?
                new ObjectParameter("FishID", fishID) :
                new ObjectParameter("FishID", typeof(int));
    
            var timeOfDeathParameter = timeOfDeath.HasValue ?
                new ObjectParameter("TimeOfDeath", timeOfDeath) :
                new ObjectParameter("TimeOfDeath", typeof(System.DateTime));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var classificationParameter = classification.HasValue ?
                new ObjectParameter("Classification", classification) :
                new ObjectParameter("Classification", typeof(int));
    
            var subClassificationParameter = subClassification.HasValue ?
                new ObjectParameter("SubClassification", subClassification) :
                new ObjectParameter("SubClassification", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RecordFishDeath", fishIDParameter, timeOfDeathParameter, descriptionParameter, classificationParameter, subClassificationParameter);
        }
    }
}
