//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishTypes : IFishTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FishTypes()
        {
            this.FishTypeDiseaseAffection = new HashSet<FishTypeDiseaseAffection>();
        }
    
        public int pk_FishTypeID { get; set; }
        public string FishTypeName { get; set; }
        public string FishTypeImagePath { get; set; }
        public string FishFeederType { get; set; }
        public string FishBirthingType { get; set; }
        public Nullable<int> FishMinTankSize { get; set; }
        public string FishAgressionLevel { get; set; }
        public string FishTerritorialLevel { get; set; }
        public int fk_WaterType { get; set; }
        public Nullable<int> fk_CareGuideID { get; set; }
    
        public virtual FishCareGuides FishCareGuides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FishTypeDiseaseAffection> FishTypeDiseaseAffection { get; set; }
        public virtual List_WaterTypes List_WaterTypes { get; set; }
    }
}
