//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FishTypes()
        {
            this.FishTypeDiseaseAffection = new HashSet<FishTypeDiseaseAffection>();
            this.UserFishInventory = new HashSet<UserFishInventory>();
        }
    
        public int pk_FishTypeID { get; set; }
        public string TypeName { get; set; }
        public int fk_FishFamily { get; set; }
        public double TankPopulationEncumbrance { get; set; }
        public string FishTypeImagePath { get; set; }
        public int fk_FishFeederType { get; set; }
        public int fk_BirthingType { get; set; }
        public Nullable<int> FishMinTankSize { get; set; }
        public int fk_FishAgressionLevel { get; set; }
        public int fk_FishTerritorialLevel { get; set; }
        public int fk_WaterType { get; set; }
        public Nullable<int> fk_CareGuideID { get; set; }
    
        public virtual FishCareGuides FishCareGuides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FishTypeDiseaseAffection> FishTypeDiseaseAffection { get; set; }
        public virtual List_FishAgressionLevels List_FishAgressionLevels { get; set; }
        public virtual List_FishFamilyTypes List_FishFamilyTypes { get; set; }
        public virtual List_FishFeedingTypes List_FishFeedingTypes { get; set; }
        public virtual List_FishTerritorialLevels List_FishTerritorialLevels { get; set; }
        public virtual List_FishFamilyTypes List_FishFamilyTypes1 { get; set; }
        public virtual List_WaterTypes List_WaterTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFishInventory> UserFishInventory { get; set; }
    }
}
