//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishTypeDiseaseAffection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FishTypeDiseaseAffection()
        {
            this.List_FishSicknessTypes = new HashSet<List_FishSicknessTypes>();
        }
    
        public int pk_AffectedTypesID { get; set; }
        public int fk_SicknessID { get; set; }
        public int fk_FishTypeID { get; set; }
    
        public virtual FishTypes FishTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List_FishSicknessTypes> List_FishSicknessTypes { get; set; }
    }
}
