//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_MedicalSubClassifications
    {
        public int pk_SubClassificationID { get; set; }
        public int fk_ParentClassificationID { get; set; }
        public string Classification { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
    
        public virtual List_MedicalClassifications List_MedicalClassifications { get; set; }
    }
}
