//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_SupplyTypes
    {
        public int pk_SupplyID { get; set; }
        public string SupplyName { get; set; }
        public int fk_PurchaseCategory { get; set; }
    
        public virtual List_PurchaseCategories List_PurchaseCategories { get; set; }
    }
}
