//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_ErrorTypes
    {
        public int pk_ErrorTypeID { get; set; }
        public string ErrorTypeDescription { get; set; }
        public int fk_ErrorSeverity { get; set; }
        public Nullable<int> fk_ErrorWaterType { get; set; }
        public string ErrorTypeCategory { get; set; }
    
        public virtual List_WaterTypes List_WaterTypes { get; set; }
    }
}
