//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_AnimalTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public List_AnimalTypes()
        {
            this.List_FishFamilyTypes = new HashSet<List_FishFamilyTypes>();
        }
    
        public int pk_AnimalTypeID { get; set; }
        public Nullable<int> fk_FishCareGuideID { get; set; }
        public string AnimalTypeName { get; set; }
    
        public virtual FishCareGuides FishCareGuides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List_FishFamilyTypes> List_FishFamilyTypes { get; set; }
    }
}
