//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_FishSicknessTypes
    {
        public int pk_FishSicknesses { get; set; }
        public string SicknessName { get; set; }
        public string IsFatal { get; set; }
        public string Symptoms { get; set; }
        public string CareNeeded { get; set; }
        public string RecoveryTime { get; set; }
        public Nullable<int> fk_AffectedTypes { get; set; }
    
        public virtual FishTypeDiseaseAffection FishTypeDiseaseAffection { get; set; }
    }
}
