//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_ErrorTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public List_ErrorTypes()
        {
            this.UserNotifications = new HashSet<UserNotifications>();
        }
    
        public int pk_ErrorTypeID { get; set; }
        public string ErrorTypeDescription { get; set; }
        public int fk_ErrorSeverity { get; set; }
        public Nullable<int> fk_ErrorWaterType { get; set; }
        public int fk_ErrorCategory { get; set; }
    
        public virtual List_ErrorCategories List_ErrorCategories { get; set; }
        public virtual List_WaterTypes List_WaterTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotifications> UserNotifications { get; set; }
    }
}
