//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_LivePlantDiseases
    {
        public int pk_PlantDiseaseID { get; set; }
        public string DiseaseName { get; set; }
        public string DiseaseDescription { get; set; }
        public string DiseasePhoto { get; set; }
        public string DiseaseCause { get; set; }
        public string DiseaseControlMeasure { get; set; }
        public Nullable<int> fk_AffectedPlants { get; set; }
    }
}
