//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreWeeklySchedules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreWeeklySchedules()
        {
            this.Stores = new HashSet<Stores>();
        }
    
        public int pk_WeeklyScheduleID { get; set; }
        public string IsOpenMonday { get; set; }
        public string IsOpenTuesday { get; set; }
        public string IsOpenWednesday { get; set; }
        public string IsOpenThursday { get; set; }
        public string IsOpenFriday { get; set; }
        public string IsOpenSaturday { get; set; }
        public string IsOpenSunday { get; set; }
        public Nullable<System.DateTime> MondayHours { get; set; }
        public Nullable<System.DateTime> TuesdayHours { get; set; }
        public Nullable<System.DateTime> WednesdayHours { get; set; }
        public Nullable<System.DateTime> ThursdayHours { get; set; }
        public Nullable<System.DateTime> FridayHours { get; set; }
        public Nullable<System.DateTime> SaturdayHours { get; set; }
        public Nullable<System.DateTime> SundayHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stores> Stores { get; set; }
    }
}
