//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreHolidaySchedules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreHolidaySchedules()
        {
            this.Stores = new HashSet<Stores>();
        }
    
        public int pk_StoreHolidayScheduleID { get; set; }
        public string NewYearsEve { get; set; }
        public string NewYearsDay { get; set; }
        public string ChristmasEve { get; set; }
        public string ChristmasDay { get; set; }
        public string ValentinesDay { get; set; }
        public string LaborDay { get; set; }
        public string MemorialDay { get; set; }
        public string IndependenceDay { get; set; }
        public string VeteransDay { get; set; }
        public string PresidentsDay { get; set; }
        public string Halloween { get; set; }
        public string Thanksgiving { get; set; }
        public string BlackFriday { get; set; }
        public string ColumbusDay { get; set; }
        public string MartinLutherKingJrDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stores> Stores { get; set; }
    }
}
