//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfiles
    {
        public int pk_ProfileID { get; set; }
        public int fk_userID { get; set; }
        public Nullable<int> fk_ContactInfo { get; set; }
        public string HasMobileAccess { get; set; }
    
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual Users Users { get; set; }
    }
}
