//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTankSupplyInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTankSupplyInventory()
        {
            this.UserPurchases = new HashSet<UserPurchases>();
        }
    
        public int pk_SupplyID { get; set; }
        public int QuantityOnHand { get; set; }
        public int fk_PurchaseID { get; set; }
        public int fk_UserID { get; set; }
        public int fk_UserTankID { get; set; }
        public Nullable<int> ExpirationDays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPurchases> UserPurchases { get; set; }
        public virtual Users Users { get; set; }
        public virtual UserTanks UserTanks { get; set; }
    }
}
