//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPurchases
    {
        public int pk_PurchaseID { get; set; }
        public string Date { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> fk_StoreID { get; set; }
        public Nullable<int> fk_PurchaseCategory { get; set; }
        public decimal Cost { get; set; }
        public int fk_UserID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ExtCost { get; set; }
        public Nullable<int> fk_UserFish { get; set; }
        public Nullable<int> fk_UserSupplyInventory { get; set; }
        public Nullable<int> fk_UserTank { get; set; }
        public Nullable<int> fk_UserPlant { get; set; }
    
        public virtual List_PurchaseCategories List_PurchaseCategories { get; set; }
        public virtual Stores Stores { get; set; }
        public virtual UserFish UserFish { get; set; }
        public virtual UserLivePlants UserLivePlants { get; set; }
        public virtual UserTanks UserTanks { get; set; }
        public virtual UserTankSupplyInventory UserTankSupplyInventory { get; set; }
    }
}
