//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPurchases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserPurchases()
        {
            this.UserLivePlants = new HashSet<UserLivePlants>();
        }
    
        public int pk_PurchaseID { get; set; }
        public string Date { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> fk_StoreID { get; set; }
        public Nullable<int> fk_PurchaseCategory { get; set; }
        public double Cost { get; set; }
        public int fk_UserID { get; set; }
    
        public virtual List_PurchaseCategories List_PurchaseCategories { get; set; }
        public virtual Stores Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLivePlants> UserLivePlants { get; set; }
        public virtual Users Users { get; set; }
    }
}
