//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserFish()
        {
            this.UserFishMedicalRecords = new HashSet<UserFishMedicalRecords>();
        }
    
        public int pk_UserFishID { get; set; }
        public int fk_FishTypeID { get; set; }
        public int fk_OwnerID { get; set; }
        public int fk_TankID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public string IsAlive { get; set; }
        public Nullable<int> fk_StoreID { get; set; }
        public string FishNotes { get; set; }
        public string ScientificName { get; set; }
        public Nullable<double> SizeLength { get; set; }
        public string FriendlyName { get; set; }
        public int fk_TerritorialLevel { get; set; }
        public Nullable<double> FishMinPH { get; set; }
        public Nullable<double> FishMaxPH { get; set; }
        public Nullable<double> FishMinTemp { get; set; }
        public Nullable<double> FishMaxTemp { get; set; }
        public int fk_FeederType { get; set; }
        public string CommonName { get; set; }
        public int fk_BirthingMethod { get; set; }
        public int fk_AgressionLevel { get; set; }
        public int fk_FishFamily { get; set; }
    
        public virtual List_FishAgressionLevels List_FishAgressionLevels { get; set; }
        public virtual List_FishBirthingTypes List_FishBirthingTypes { get; set; }
        public virtual List_FishFamilyTypes List_FishFamilyTypes { get; set; }
        public virtual List_FishFeedingTypes List_FishFeedingTypes { get; set; }
        public virtual List_FishTerritorialLevels List_FishTerritorialLevels { get; set; }
        public virtual List_WaterTypes List_WaterTypes { get; set; }
        public virtual Stores Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFishMedicalRecords> UserFishMedicalRecords { get; set; }
        public virtual Users Users { get; set; }
        public virtual UserTanks UserTanks { get; set; }
    }
}
