//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFish
    {
        public int pk_FishID { get; set; }
        public int fk_FishTypeID { get; set; }
        public int fk_OwnerID { get; set; }
        public int fk_TankID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public string IsAlive { get; set; }
        public Nullable<int> fk_PurchaseLocation { get; set; }
        public string FishNotes { get; set; }
    
        public virtual FishTypes FishTypes { get; set; }
        public virtual Users Users { get; set; }
        public virtual UserTanks UserTanks { get; set; }
    }
}
