//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermissions
    {
        public int pk_PermissionID { get; set; }
        public bool AddSuperAdminUser { get; set; }
        public bool AddProgramUsers { get; set; }
        public bool AddPurchase { get; set; }
        public bool AddSupply { get; set; }
        public bool AddDecoration { get; set; }
        public bool AddFish { get; set; }
        public bool AddLivePlant { get; set; }
        public bool AddTank { get; set; }
        public bool EditProgramUsers { get; set; }
        public bool EditPurchase { get; set; }
        public bool EditSupply { get; set; }
        public bool EditDecoration { get; set; }
        public bool EditFish { get; set; }
        public bool EditLivePlant { get; set; }
        public bool EditTank { get; set; }
        public bool DeleteProgramUsers { get; set; }
        public bool DeletePurchase { get; set; }
        public bool DeleteSupply { get; set; }
        public bool DeleteDecoration { get; set; }
        public bool DeleteFish { get; set; }
        public bool DeletePlant { get; set; }
        public bool DeleteTank { get; set; }
        public bool RecordDeath { get; set; }
        public bool PerformMaintenance { get; set; }
        public bool LoginGlobal { get; set; }
        public bool LoginWeb { get; set; }
        public bool LoginMobile { get; set; }
        public bool LoginDesktop { get; set; }
        public bool LoginAPI { get; set; }
        public bool ViewGlobalProgramUsers { get; set; }
        public bool ViewGlobalFish { get; set; }
        public bool ViewGlobalSupplies { get; set; }
        public bool ViewGlobalDecorations { get; set; }
        public bool ViewGlobalTanks { get; set; }
        public bool ViewGlobalPlants { get; set; }
        public bool ViewGlobalPurchases { get; set; }
        public bool RecordGlobalDeath { get; set; }
        public bool PerformGlobalMaintenance { get; set; }
    }
}
