//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFishMedicalRecords
    {
        public int pk_MedRecordID { get; set; }
        public System.DateTime RecordDate { get; set; }
        public int fk_FishID { get; set; }
        public string Description { get; set; }
        public int fk_UserID { get; set; }
    
        public virtual UserFish UserFish { get; set; }
        public virtual Users Users { get; set; }
    }
}
