//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFishInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserFishInventory()
        {
            this.UserFishMedicalRecords = new HashSet<UserFishMedicalRecords>();
        }
    
        public int pk_FishID { get; set; }
        public Nullable<int> fk_UserID { get; set; }
        public Nullable<int> fk_UserFishID { get; set; }
        public Nullable<int> fk_UserPurchaseID { get; set; }
        public Nullable<int> fk_FishType { get; set; }
        public Nullable<int> fk_UserTank { get; set; }
    
        public virtual FishTypes FishTypes { get; set; }
        public virtual UserFish UserFish { get; set; }
        public virtual UserPurchases UserPurchases { get; set; }
        public virtual Users Users { get; set; }
        public virtual UserTanks UserTanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFishMedicalRecords> UserFishMedicalRecords { get; set; }
    }
}
