//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTankTests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTankTests()
        {
            this.UserTankTemperatureLogs = new HashSet<UserTankTemperatureLogs>();
        }
    
        public int pk_TestID { get; set; }
        public System.DateTime TestDate { get; set; }
        public int fk_UserTank { get; set; }
        public int fk_TestType { get; set; }
        public Nullable<double> NitriteLevel { get; set; }
        public Nullable<double> NitrateLevel { get; set; }
        public Nullable<double> gHLevel { get; set; }
        public Nullable<double> cHLevel { get; set; }
        public Nullable<double> pHLevel { get; set; }
        public string ActionsTaken { get; set; }
    
        public virtual List_TankTestTypes List_TankTestTypes { get; set; }
        public virtual UserTanks UserTanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTankTemperatureLogs> UserTankTemperatureLogs { get; set; }
    }
}
