//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActionLogs
    {
        public int pk_ActionID { get; set; }
        public int fk_UserID { get; set; }
        public int fk_UserActionType { get; set; }
    
        public virtual List_ActionTypes List_ActionTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
