//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLivePlants
    {
        public int pk_UserPlantID { get; set; }
        public int fk_UserID { get; set; }
        public int fk_TankID { get; set; }
        public Nullable<int> fk_PurchaseID { get; set; }
        public int fk_PlantType { get; set; }
    
        public virtual LivePlantTypes LivePlantTypes { get; set; }
        public virtual Users Users { get; set; }
        public virtual UserTanks UserTanks { get; set; }
    }
}
