//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTankTemperatureLogs
    {
        public int pk_TempLogID { get; set; }
        public int fk_UserTank { get; set; }
        public double Temperature { get; set; }
        public System.DateTime LogDate { get; set; }
        public string LogNotes { get; set; }
        public Nullable<int> fk_TestID { get; set; }
    
        public virtual UserTanks UserTanks { get; set; }
    }
}
