//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTanks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTanks()
        {
            this.Purchases = new HashSet<Purchases>();
            this.UserFish = new HashSet<UserFish>();
        }
    
        public int pk_UserTankID { get; set; }
        public int fk_TankOwner { get; set; }
        public int TankSize { get; set; }
        public string TankHeight { get; set; }
        public string TankWidth { get; set; }
        public int fk_TankWaterType { get; set; }
    
        public virtual List_WaterTypes List_WaterTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFish> UserFish { get; set; }
        public virtual Users Users { get; set; }
    }
}
