//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FishDictionary
    {
        public int Fish_ID { get; set; }
        public string Fish_Type { get; set; }
        public string FishImageFilepath { get; set; }
        public Nullable<int> Minimum_Tank__gallons_ { get; set; }
        public string Water_Type { get; set; }
        public string Water_Notes { get; set; }
        public string Birthing_Type { get; set; }
        public string Birthing_Notes { get; set; }
        public string Feeding_Type { get; set; }
        public string Care_Guide_Filepath { get; set; }
        public string Mentality_Agression { get; set; }
        public string Fish_Family { get; set; }
        public string Mentality_Territorial { get; set; }
    }
}
