//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MasterFishView
    {
        public int IsAlive { get; set; }
        public string FishNotes { get; set; }
        public Nullable<double> SizeLength { get; set; }
        public string FriendlyName { get; set; }
        public Nullable<System.DateTime> LastTankMove { get; set; }
        public string ColorName { get; set; }
        public string SecondaryColor { get; set; }
        public string UserName { get; set; }
        public string TypeName { get; set; }
        public double TankPopulationEncumbrance { get; set; }
        public string FishTypeImagePath { get; set; }
        public Nullable<int> FishMinTankSize { get; set; }
        public string PurchaseDate { get; set; }
        public decimal PurchaseCost { get; set; }
        public string Description { get; set; }
        public string TankDisplayName { get; set; }
        public int TankSize { get; set; }
        public string WaterTypeName { get; set; }
        public string StoreName { get; set; }
        public string TerritorialLevel { get; set; }
        public string AgressionLevel { get; set; }
        public string FeedingType { get; set; }
        public string BirthingType { get; set; }
    }
}
