//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PlantDictionary
    {
        public int TypeID { get; set; }
        public string PlantType { get; set; }
        public bool Fertilizer { get; set; }
        public bool Floatable { get; set; }
        public int MinTemp { get; set; }
        public int MaxTemp { get; set; }
        public Nullable<int> IdealTemp { get; set; }
        public Nullable<double> MaxInches { get; set; }
        public string Image { get; set; }
        public string ItemType { get; set; }
        public string Lighting { get; set; }
        public string PlantSize { get; set; }
    }
}
