//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserTanks
    {
        public int Tank_ID { get; set; }
        public int TankSize { get; set; }
        public string TankHeight { get; set; }
        public string TankWidth { get; set; }
        public string TypeName { get; set; }
        public string TankSpecialTags { get; set; }
        public string TankShape { get; set; }
        public string WaterTypeName { get; set; }
        public string WaterTypeSpecialTags { get; set; }
        public string UserName { get; set; }
        public Nullable<int> NumFish { get; set; }
    }
}
