//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserFish
    {
        public int Fish_ID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public string IsAlive { get; set; }
        public string FishNotes { get; set; }
        public string ScientificName { get; set; }
        public Nullable<double> SizeLength { get; set; }
        public string FriendlyName { get; set; }
        public Nullable<double> FishMinPH { get; set; }
        public Nullable<double> FishMaxPH { get; set; }
        public Nullable<double> FishMinTemp { get; set; }
        public Nullable<double> FishMaxTemp { get; set; }
        public string CommonName { get; set; }
        public string UserName { get; set; }
        public string FishFamilyName { get; set; }
        public string AnimalTypeName { get; set; }
        public Nullable<int> TankSize { get; set; }
        public string TankHeight { get; set; }
        public string TankWidth { get; set; }
        public string AgressionLevel { get; set; }
        public string TerritorialLevel { get; set; }
        public string FeedingType { get; set; }
        public string BirthingType { get; set; }
        public string SpecialNotes { get; set; }
    }
}
