//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserTanks
    {
        public int pk_UserTankID { get; set; }
        public string UserName { get; set; }
        public int TankSize { get; set; }
        public string TankHeight { get; set; }
        public string TankWidth { get; set; }
        public int fk_TankWaterType { get; set; }
        public int fk_TankType { get; set; }
        public string TankDisplayName { get; set; }
        public bool IsActiveTank { get; set; }
    }
}
