//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserFish
    {
        public string AnimalType { get; set; }
        public string FishType { get; set; }
        public string FriendlyName { get; set; }
        public string Color { get; set; }
        public Nullable<int> MinTankSize { get; set; }
        public bool IsAlive { get; set; }
        public string FishNotes { get; set; }
        public Nullable<double> SizeLength { get; set; }
        public string BirthingType { get; set; }
        public string SpecialNotes { get; set; }
        public string FeedingType { get; set; }
        public string FishFamilyName { get; set; }
        public string AgressionLevel { get; set; }
        public string TerritorialLevel { get; set; }
        public string ImagePath { get; set; }
        public string PurchaseDate { get; set; }
        public double PurchaseCost { get; set; }
        public string Description { get; set; }
        public int GallonSize { get; set; }
        public string TankName { get; set; }
        public string WaterType { get; set; }
        public string AnimalOwner { get; set; }
        public int fk_UserFishInventory { get; set; }
    }
}
