//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatiLife_Inventory_DataAccess.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserSessions
    {
        public string Session_ID { get; set; }
        public string Session_Begin_Time { get; set; }
        public string Session_User_Permissions { get; set; }
        public string Session_End_Time { get; set; }
        public bool Session_Active { get; set; }
        public string Session_Duration { get; set; }
    }
}
